# ??? App Config ???????????????????????????????????????????
spring.application.name=hostel-backend
server.port=8080

# ??? MongoDB Atlas ????????????????????????????????????????
spring.data.mongodb.uri=mongodb+srv://hostelAdmin:jeganraj@hostel-platform.cbfftu8.mongodb.net/hosteldb?retryWrites=true&w=majority&appName=hostel-platform


# ??? Redis (Upstash) ??????????????????????????????????????
spring.data.redis.url=rediss://default:gQAAAAAAAeaZAAIgcDFhN2U5ZDA4NDE1MmQ0YzE3ODk2MzUwMzI2OGY4M2RkMA@related-jawfish-124569.upstash.io:6379
spring.data.redis.ssl.enabled=true

# ??? JWT Config ???????????????????????????????????????????
jwt.secret=SmartHostelPlatformSecretKey2006JeganrajProjectVeryLongSecureKey123456789
jwt.access.expiration=900000
jwt.refresh.expiration=604800000

# ??? Email (Resend via SMTP) ??????????????????????????????
spring.mail.host=smtp.resend.com
spring.mail.port=465
spring.mail.username=resend
spring.mail.password=re_FJ8afSYU_49uuaXRs9FjhKp9KVczA8ELZ
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true

# ??? Cloudinary ???????????????????????????????????????????
cloudinary.cloud-name=db2hj7bkn
cloudinary.api-key=814347888112172
cloudinary.api-secret=Dxvhxy1ZApS9-EJriWMKitL2QDk

# ??? File Upload Size Limit ???????????????????????????????
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# ??? Logging ??????????????????????????????????????????????
logging.level.org.springframework.security=DEBUG
logging.level.com.hostel=DEBUG

